@echo off
REM This script is meant to convert the Volvo VIDA database into CSV files, for modular usage without SQL Server and VIDA on other devices.
REM Note that while originally autogenerated, some individual lines had to be modified because some data contained commas, which broke the CSV files.
REM Of course, this could be done using Powershell's Invoke-Sqlcmd and Export-Csv, but I simply couldn't get those to work on my VIDA machine.

REM The following commands were generated using this SQL expression: (from https://stackoverflow.com/a/75209355/9156308)
REM SELECT 'sqlcmd -s, -W -Q "set nocount on; select * from ['+DB_NAME()+'].[dbo].[' + st.NAME + ']" | findstr /v /c:"-" /b > "csv/' +st.NAME +'.csv'
REM FROM sys.tables st

REM They only include additional username, password, and server name arguments.

REM basedata
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[VINDecodeVariant]" | findstr /v /c:"-" /b > "csv/basedata/VINDecodeVariant.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[VehicleModel]" | findstr /v /c:"-" /b > "csv/basedata/VehicleModel.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[VINVariantCodes]" | findstr /v /c:"-" /b > "csv/basedata/VINVariantCodes.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[VehicleProfilePartnerGroup]" | findstr /v /c:"-" /b > "csv/basedata/VehicleProfilePartnerGroup.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[SpecialVehicle]" | findstr /v /c:"-" /b > "csv/basedata/SpecialVehicle.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[VehicleProfile]" | findstr /v /c:"-" /b > "csv/basedata/VehicleProfile.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[SelectedProfiles]" | findstr /v /c:"-" /b > "csv/basedata/SelectedProfiles.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[ValidProfiles]" | findstr /v /c:"-" /b > "csv/basedata/ValidProfiles.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[dtproperties]" | findstr /v /c:"-" /b > "csv/basedata/dtproperties.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[DBContent]" | findstr /v /c:"-" /b > "csv/basedata/DBContent.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[DBSchema]" | findstr /v /c:"-" /b > "csv/basedata/DBSchema.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[AMYProfileMap]" | findstr /v /c:"-" /b > "csv/basedata/AMYProfileMap.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[DBStageVersion]" | findstr /v /c:"-" /b > "csv/basedata/DBStageVersion.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[BodyStyle]" | findstr /v /c:"-" /b > "csv/basedata/BodyStyle.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[BrakeSystem]" | findstr /v /c:"-" /b > "csv/basedata/BrakeSystem.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[Engine]" | findstr /v /c:"-" /b > "csv/basedata/Engine.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[ModelYear]" | findstr /v /c:"-" /b > "csv/basedata/ModelYear.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[StructureWeek]" | findstr /v /c:"-" /b > "csv/basedata/StructureWeek.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[NodeECU]" | findstr /v /c:"-" /b > "csv/basedata/NodeECU.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[PartnerGroup]" | findstr /v /c:"-" /b > "csv/basedata/PartnerGroup.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[Steering]" | findstr /v /c:"-" /b > "csv/basedata/Steering.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[Suspension]" | findstr /v /c:"-" /b > "csv/basedata/Suspension.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[Transmission]" | findstr /v /c:"-" /b > "csv/basedata/Transmission.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [basedata].[dbo].[VINDecodeModel]" | findstr /v /c:"-" /b > "csv/basedata/VINDecodeModel.csv

REM carcom
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T143_BlockDataType]" | findstr /v /c:"-" /b > "csv/carcom/T143_BlockDataType.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T154_SymptomType]" | findstr /v /c:"-" /b > "csv/carcom/T154_SymptomType.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T155_Scaling]" | findstr /v /c:"-" /b > "csv/carcom/T155_Scaling.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T163_ProfileValueType]" | findstr /v /c:"-" /b > "csv/carcom/T163_ProfileValueType.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T172_SecurityCodeType]" | findstr /v /c:"-" /b > "csv/carcom/T172_SecurityCodeType.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T192_TextCategory]" | findstr /v /c:"-" /b > "csv/carcom/T192_TextCategory.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T193_Language]" | findstr /v /c:"-" /b > "csv/carcom/T193_Language.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T199_ControlTable]" | findstr /v /c:"-" /b > "csv/carcom/T199_ControlTable.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select id,fkT102_EcuType,'""' + identifier + '""' as identifier,'""' + name + '""' as name from [carcom].[dbo].[T101_Ecu]" | findstr /v /c:"-" /b > "csv/carcom/T101_Ecu.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T111_Service]" | findstr /v /c:"-" /b > "csv/carcom/T111_Service.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T130_Init]" | findstr /v /c:"-" /b > "csv/carcom/T130_Init.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T134_InitCategory_Type]" | findstr /v /c:"-" /b > "csv/carcom/T134_InitCategory_Type.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T162_ProfileValue]" | findstr /v /c:"-" /b > "csv/carcom/T162_ProfileValue.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T171_SecurityCode]" | findstr /v /c:"-" /b > "csv/carcom/T171_SecurityCode.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T190_Text]" | findstr /v /c:"-" /b > "csv/carcom/T190_Text.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[dtproperties]" | findstr /v /c:"-" /b > "csv/carcom/dtproperties.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T100_EcuVariant]" | findstr /v /c:"-" /b > "csv/carcom/T100_EcuVariant.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T123_Bus]" | findstr /v /c:"-" /b > "csv/carcom/T123_Bus.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T131_InitValue]" | findstr /v /c:"-" /b > "csv/carcom/T131_InitValue.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select id,fkT142_BlockType,fkT143_BlockDataType,'""' + REPLACE(REPLACE(REPLACE(name, CHAR(13), ''), CHAR(10), ''), '""', '""""') + '""' as name,fkT190_Text,offset,length,exclude,composite from [carcom].[dbo].[T141_Block]" | findstr /v /c:"-" /b > "csv/carcom/T141_Block.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T156_SymptomSection]" | findstr /v /c:"-" /b > "csv/carcom/T156_SymptomSection.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select id,identifier,folderLevel,'""' + description + '""' as description,title,fkT162_ProfileValue_Model,fkT162_ProfileValue_Year,fkT162_ProfileValue_Engine,fkT162_ProfileValue_Transmission,fkT162_ProfileValue_Body,fkT162_ProfileValue_Steering,fkT162_ProfileValue_Market,fkT162_ProfileValue_ControlUnit,fkT162_ProfileValue_ChassisFrom,fkT162_ProfileValue_ChassisTo from [carcom].[dbo].[T161_Profile]" | findstr /v /c:"-" /b > "csv/carcom/T161_Profile.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select fkT193_Language,fkT190_Text,status,'""' + REPLACE(REPLACE(data COLLATE Latin1_General_BIN, N'”', '""'), '""', '""""') + '""' as data from [carcom].[dbo].[T191_TextData] where fkT193_Language=19" | findstr /v /c:"-" /b > "csv/carcom/T191_TextData.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T194_FunctionGroup_1]" | findstr /v /c:"-" /b > "csv/carcom/T194_FunctionGroup_1.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T103_EcuVariant_Project]" | findstr /v /c:"-" /b > "csv/carcom/T103_EcuVariant_Project.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T110_Service_EcuVariant]" | findstr /v /c:"-" /b > "csv/carcom/T110_Service_EcuVariant.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T121_Config]" | findstr /v /c:"-" /b > "csv/carcom/T121_Config.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T136_InitHw_Profile]" | findstr /v /c:"-" /b > "csv/carcom/T136_InitHw_Profile.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T137_InitSwdl_Profile]" | findstr /v /c:"-" /b > "csv/carcom/T137_InitSwdl_Profile.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T144_BlockChild]" | findstr /v /c:"-" /b > "csv/carcom/T144_BlockChild.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select Id,fkT141_Block,SortOrder,'""' + CompareValue + '""' as CompareValue,Operator,fkT190_Text_Value,fkT190_Text_Unit,fkT155_Scaling,altDisplayValue,fkT190_Text_ppeValue,fkT190_Text_ppeUnit,fkT155_ppeScaling from [carcom].[dbo].[T150_BlockValue]" | findstr /v /c:"-" /b > "csv/carcom/T150_BlockValue.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T153_SymptomCategory]" | findstr /v /c:"-" /b > "csv/carcom/T153_SymptomCategory.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T160_DefaultEcuVariant]" | findstr /v /c:"-" /b > "csv/carcom/T160_DefaultEcuVariant.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T170_SecurityCode_EcuVariant]" | findstr /v /c:"-" /b > "csv/carcom/T170_SecurityCode_EcuVariant.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T196_FunctionGroup_2]" | findstr /v /c:"-" /b > "csv/carcom/T196_FunctionGroup_2.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T120_Config_EcuVariant]" | findstr /v /c:"-" /b > "csv/carcom/T120_Config_EcuVariant.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T152_Symptom]" | findstr /v /c:"-" /b > "csv/carcom/T152_Symptom.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T158_Symptom_CSC]" | findstr /v /c:"-" /b > "csv/carcom/T158_Symptom_CSC.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T157_SymptomConnection]" | findstr /v /c:"-" /b > "csv/carcom/T157_SymptomConnection.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T159_SymptomCSC_SymptomDTC]" | findstr /v /c:"-" /b > "csv/carcom/T159_SymptomCSC_SymptomDTC.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T151_BlockValue_Symptom]" | findstr /v /c:"-" /b > "csv/carcom/T151_BlockValue_Symptom.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[DBSchema]" | findstr /v /c:"-" /b > "csv/carcom/DBSchema.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[DBContent]" | findstr /v /c:"-" /b > "csv/carcom/DBContent.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T148_BlockMetaPARA]" | findstr /v /c:"-" /b > "csv/carcom/T148_BlockMetaPARA.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[DBStageVersion]" | findstr /v /c:"-" /b > "csv/carcom/DBStageVersion.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T102_EcuType]" | findstr /v /c:"-" /b > "csv/carcom/T102_EcuType.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T104_Project]" | findstr /v /c:"-" /b > "csv/carcom/T104_Project.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T122_Protocol]" | findstr /v /c:"-" /b > "csv/carcom/T122_Protocol.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T124_Net]" | findstr /v /c:"-" /b > "csv/carcom/T124_Net.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T132_InitValueType]" | findstr /v /c:"-" /b > "csv/carcom/T132_InitValueType.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T133_InitCategory]" | findstr /v /c:"-" /b > "csv/carcom/T133_InitCategory.csv
sqlcmd -S WIN-JR1TF78ROOI\VIDA -U sa -P GunnarS3g3 -s, -W -Q "set nocount on; select * from [carcom].[dbo].[T142_BlockType]" | findstr /v /c:"-" /b > "csv/carcom/T142_BlockType.csv
